// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Repository;
using System;

namespace UPCTaggingInterface.Migrations
{
    [DbContext(typeof(UPCTaggingDBContext))]
    [Migration("20180315102818_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Repositories.Entities.ProductCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("categoryid");

                    b.Property<string>("CategoryName")
                        .HasColumnName("category");

                    b.HasKey("CategoryID");

                    b.ToTable("category");
                });

            modelBuilder.Entity("Repositories.Entities.ProductSubCategory", b =>
                {
                    b.Property<int>("SubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("subcategoryid");

                    b.Property<string>("SubcategoryName")
                        .HasColumnName("subcategory");

                    b.HasKey("SubCategoryID");

                    b.ToTable("subcategory");
                });

            modelBuilder.Entity("Repositories.Entities.ProductType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("typeid");

                    b.Property<string>("ProductTypeName")
                        .HasColumnName("producttype")
                        .HasMaxLength(255);

                    b.HasKey("TypeID");

                    b.ToTable("producttype");
                });

            modelBuilder.Entity("Repositories.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName");

                    b.HasKey("RoleID");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Repositories.Entities.TaggedUPC", b =>
                {
                    b.Property<string>("UPCCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("upccode");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasMaxLength(255);

                    b.Property<int>("DescriptionID")
                        .HasColumnName("descriptionid");

                    b.Property<int?>("ProductCategoryID")
                        .HasColumnName("productcategoryid");

                    b.Property<string>("ProductSizing")
                        .HasColumnName("productsizing");

                    b.Property<int?>("ProductSubcategoryID")
                        .HasColumnName("productsubcategoryid");

                    b.Property<int?>("ProductTypeID")
                        .HasColumnName("producttypeid");

                    b.HasKey("UPCCode");

                    b.HasIndex("ProductCategoryID");

                    b.HasIndex("ProductSubcategoryID");

                    b.HasIndex("ProductTypeID");

                    b.ToTable("taggedupc");
                });

            modelBuilder.Entity("Repositories.Entities.UntaggedUPC", b =>
                {
                    b.Property<int>("UntaggedUPCID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("untaggedupcid");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasMaxLength(255);

                    b.Property<int>("DescriptionID")
                        .HasColumnName("descriptionid");

                    b.Property<int?>("ItemAssignedBy")
                        .HasColumnName("itemassignedby");

                    b.Property<int?>("ItemAssignedToFk")
                        .HasColumnName("itemassingedto");

                    b.Property<DateTime?>("ItemInsertedAt")
                        .HasColumnName("iteminsertedat")
                        .HasColumnType("timestamp");

                    b.Property<int?>("ItemInsertedBy")
                        .HasColumnName("iteminsertedby");

                    b.Property<DateTime?>("ItemModifiedAt")
                        .HasColumnName("itemmodifiedat")
                        .HasColumnType("timestamp");

                    b.Property<int?>("ItemModifiedBy")
                        .HasColumnName("itemmodifiedby");

                    b.Property<int?>("ProductCategoryID")
                        .HasColumnName("productcategoryid");

                    b.Property<string>("ProductSizing")
                        .HasColumnName("productsizing");

                    b.Property<int?>("ProductSubcategoryID")
                        .HasColumnName("productsubcategoryid");

                    b.Property<int?>("ProductTypeID")
                        .HasColumnName("producttypeid");

                    b.Property<int?>("StatusID")
                        .HasColumnName("statusid");

                    b.Property<string>("UPCCode")
                        .HasColumnName("upccode");

                    b.Property<int?>("itemassingedto");

                    b.Property<int?>("productcategoryid");

                    b.Property<int?>("productsubcategoryid");

                    b.Property<int?>("producttypeid");

                    b.HasKey("UntaggedUPCID");

                    b.HasIndex("itemassingedto");

                    b.HasIndex("productcategoryid");

                    b.HasIndex("productsubcategoryid");

                    b.HasIndex("producttypeid");

                    b.ToTable("untaggedupc");
                });

            modelBuilder.Entity("Repositories.Entities.UPCHistory", b =>
                {
                    b.Property<long>("UPCHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("upchistoryid");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnName("approvedby");

                    b.Property<DateTime>("ItemInsertedAt")
                        .HasColumnName("iteminsertedat");

                    b.Property<DateTime>("ItemModifiedAt")
                        .HasColumnName("itemmodifiedat");

                    b.Property<int?>("ModifiedApprovedBy")
                        .HasColumnName("modifiedapprovedby");

                    b.Property<int?>("ModifiedSubmittedBy")
                        .HasColumnName("modifiedsubmittedby");

                    b.Property<int?>("SubmittedBy")
                        .HasColumnName("submittedby");

                    b.Property<string>("TaggedUPCCode")
                        .HasColumnName("taggedupccode");

                    b.Property<string>("TaggedUPCUPCCode");

                    b.HasKey("UPCHistoryID");

                    b.HasIndex("TaggedUPCUPCCode");

                    b.ToTable("upchistory");
                });

            modelBuilder.Entity("Repositories.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("userid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnName("accessfailedcount");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnName("concurrencystamp");

                    b.Property<string>("Email")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnName("emailconfirmed");

                    b.Property<string>("Id")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnName("isenabled");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnName("lockoutenabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnName("lockoutend");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnName("normalizedemail");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnName("normalizedusername");

                    b.Property<string>("PasswordHash")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("phonenumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnName("phonenumberconfirmed");

                    b.Property<int>("RoleID")
                        .HasColumnName("userroleid");

                    b.Property<string>("SecurityStamp")
                        .HasColumnName("securitystamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnName("twofactorenabled");

                    b.Property<string>("UserName")
                        .HasColumnName("username");

                    b.HasKey("UserID")
                        .HasName("userid");

                    b.ToTable("upcuser");
                });

            modelBuilder.Entity("Repositories.Entities.TaggedUPC", b =>
                {
                    b.HasOne("Repositories.Entities.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryID");

                    b.HasOne("Repositories.Entities.ProductSubCategory", "ProductSubCategory")
                        .WithMany()
                        .HasForeignKey("ProductSubcategoryID");

                    b.HasOne("Repositories.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeID");
                });

            modelBuilder.Entity("Repositories.Entities.UntaggedUPC", b =>
                {
                    b.HasOne("Repositories.Entities.User", "ItemAssignedTo")
                        .WithMany()
                        .HasForeignKey("itemassingedto");

                    b.HasOne("Repositories.Entities.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("productcategoryid");

                    b.HasOne("Repositories.Entities.ProductSubCategory", "ProductSubCategory")
                        .WithMany()
                        .HasForeignKey("productsubcategoryid");

                    b.HasOne("Repositories.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("producttypeid");
                });

            modelBuilder.Entity("Repositories.Entities.UPCHistory", b =>
                {
                    b.HasOne("Repositories.Entities.TaggedUPC", "TaggedUPC")
                        .WithMany()
                        .HasForeignKey("TaggedUPCUPCCode");
                });
#pragma warning restore 612, 618
        }
    }
}
